<Project InitialTargets="SkipWindowsOnlyProjects">

  <!-- WinUI's XAML compiler only runs on Windows, so other OSes leave out the projects with .Windows in their names -->
  <Target Name="SkipWindowsOnlyProjects" Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <ItemGroup>
      <ProjectReference Remove="@(ProjectReference)" Condition="$([System.String]::Copy('%(Filename)').Contains('.Windows'))" />
    </ItemGroup>
  </Target>

</Project>
